planet_storages = [{'planet_lvl' : '0', 'credit_cap' : '0', 'cost' : '0'},
                       {'planet_lvl' : '1', 'credit_cap' : '1000', 'cost' : '50'},
                       {'planet_lvl' : '2', 'credit_cap' : '1400', 'cost' : '200'},
                       {'planet_lvl' : '3', 'credit_cap' : '1800', 'cost' : '500'},
                       {'planet_lvl' : '4', 'credit_cap' : '3000', 'cost' : '1000'},
                       {'planet_lvl' : '5', 'credit_cap' : '4000', 'cost' : '2000'},
                       {'planet_lvl' : '6', 'credit_cap' : '5000', 'cost' : '4000'},
                       {'planet_lvl' : '7', 'credit_cap' : '6000', 'cost' : '8000'},
                       {'planet_lvl' : '8', 'credit_cap' : '7500', 'cost' : '10000'},
                       {'planet_lvl' : '9', 'credit_cap' : '10000', 'cost' : '20000'},
                       {'planet_lvl' : '10', 'credit_cap' : '13000', 'cost' : '30000'},
                       {'planet_lvl' : '11', 'credit_cap' : '16000', 'cost' : '40000'},
                       {'planet_lvl' : '12', 'credit_cap' : '20000', 'cost' : '50000'},
                       {'planet_lvl' : '13', 'credit_cap' : '24000', 'cost' : '75000'},
                       {'planet_lvl' : '14', 'credit_cap' : '28000', 'cost' : '100000'},
                       {'planet_lvl' : '15', 'credit_cap' : '35000', 'cost' : '125000'},
                       {'planet_lvl' : '16', 'credit_cap' : '45000', 'cost' : '150000'},
                       {'planet_lvl' : '17', 'credit_cap' : '65000', 'cost' : '175000'},
                       {'planet_lvl' : '18', 'credit_cap' : '90000', 'cost' : '200000'},
                       {'planet_lvl' : '19', 'credit_cap' : '130000', 'cost' : '250000'},
                       {'planet_lvl' : '20', 'credit_cap' : '170000', 'cost' : '300000'},
                       {'planet_lvl' : '21', 'credit_cap' : '210000', 'cost' : '400000'},
                       {'planet_lvl' : '22', 'credit_cap' : '250000', 'cost' : '500000'},
                       {'planet_lvl' : '23', 'credit_cap' : '290000', 'cost' : '600000'},
                       {'planet_lvl' : '24', 'credit_cap' : '330000', 'cost' : '800000'},
                       {'planet_lvl' : '25', 'credit_cap' : '370000', 'cost' : '1000000'},
                       {'planet_lvl' : '26', 'credit_cap' : '410000', 'cost' : '1250000'},
                       {'planet_lvl' : '27', 'credit_cap' : '450000', 'cost' : '1500000'},
                       {'planet_lvl' : '28', 'credit_cap' : '490000', 'cost' : '1750000'},
                       {'planet_lvl' : '29', 'credit_cap' : '530000', 'cost' : '2000000'},
                       {'planet_lvl' : '30', 'credit_cap' : '570000', 'cost' : '2250000'},
                       {'planet_lvl' : '31', 'credit_cap' : '610000', 'cost' : '2500000'},
                       {'planet_lvl' : '32', 'credit_cap' : '650000', 'cost' : '2750000'},
                       {'planet_lvl' : '33', 'credit_cap' : '690000', 'cost' : '3000000'},
                       {'planet_lvl' : '34', 'credit_cap' : '730000', 'cost' : '3500000'},
                       {'planet_lvl' : '35', 'credit_cap' : '770000', 'cost' : '4000000'},
                       {'planet_lvl' : '36', 'credit_cap' : '810000', 'cost' : '4500000'},
                       {'planet_lvl' : '37', 'credit_cap' : '850000', 'cost' : '5000000'},
                       {'planet_lvl' : '38', 'credit_cap' : '850000', 'cost' : '5500000'},
                       {'planet_lvl' : '39', 'credit_cap' : '850000', 'cost' : '6000000'},
                       {'planet_lvl' : '40', 'credit_cap' : '850000', 'cost' : '0'}]

desert1 = [{'planet_lvl' : '1', 'ship_per_hour' : '87'},
           {'planet_lvl' : '2', 'ship_per_hour' : '94'},
           {'planet_lvl' : '3', 'ship_per_hour' : '102'},
           {'planet_lvl' : '4', 'ship_per_hour' : '110'},
           {'planet_lvl' : '5', 'ship_per_hour' : '119'},
           {'planet_lvl' : '6', 'ship_per_hour' : '128'},
           {'planet_lvl' : '7', 'ship_per_hour' : '138'},
           {'planet_lvl' : '8', 'ship_per_hour' : '149'},
           {'planet_lvl' : '9', 'ship_per_hour' : '161'},
           {'planet_lvl' : '10', 'ship_per_hour' : '174'},
           {'planet_lvl' : '11', 'ship_per_hour' : '188'},
           {'planet_lvl' : '12', 'ship_per_hour' : '203'},
           {'planet_lvl' : '13', 'ship_per_hour' : '220'},
           {'planet_lvl' : '14', 'ship_per_hour' : '237'},
           {'planet_lvl' : '15', 'ship_per_hour' : '256'},]

desert3 = [{'planet_lvl' : '1', 'ship_per_hour' : '93'},
           {'planet_lvl' : '2', 'ship_per_hour' : '101'},
           {'planet_lvl' : '3', 'ship_per_hour' : '109'},
           {'planet_lvl' : '4', 'ship_per_hour' : '118'},
           {'planet_lvl' : '5', 'ship_per_hour' : '127'},
           {'planet_lvl' : '6', 'ship_per_hour' : '137'},
           {'planet_lvl' : '7', 'ship_per_hour' : '148'},
           {'planet_lvl' : '8', 'ship_per_hour' : '160'},
           {'planet_lvl' : '9', 'ship_per_hour' : '173'},
           {'planet_lvl' : '10', 'ship_per_hour' : '187'},
           {'planet_lvl' : '11', 'ship_per_hour' : '202'},
           {'planet_lvl' : '12', 'ship_per_hour' : '218'},
           {'planet_lvl' : '13', 'ship_per_hour' : '235'},
           {'planet_lvl' : '14', 'ship_per_hour' : '254'},
           {'planet_lvl' : '15', 'ship_per_hour' : '275'},
           {'planet_lvl' : '16', 'ship_per_hour' : '297'},
           {'planet_lvl' : '17', 'ship_per_hour' : '312'},
           {'planet_lvl' : '18', 'ship_per_hour' : '334'},
           {'planet_lvl' : '19', 'ship_per_hour' : '357'},
           {'planet_lvl' : '20', 'ship_per_hour' : '382'},
           {'planet_lvl' : '21', 'ship_per_hour' : '409'},
           {'planet_lvl' : '22', 'ship_per_hour' : '438'},
           {'planet_lvl' : '23', 'ship_per_hour' : '468'},
           {'planet_lvl' : '24', 'ship_per_hour' : '501'},
           {'planet_lvl' : '25', 'ship_per_hour' : '536'},
           {'planet_lvl' : '26', 'ship_per_hour' : '574'},
           {'planet_lvl' : '27', 'ship_per_hour' : '614'},
           {'planet_lvl' : '28', 'ship_per_hour' : '657'},
           {'planet_lvl' : '29', 'ship_per_hour' : '703'},
           {'planet_lvl' : '30', 'ship_per_hour' : '752'},]

desert4 = [{'planet_lvl' : '1', 'ship_per_hour' : '106'},
           {'planet_lvl' : '2', 'ship_per_hour' : '114'},
           {'planet_lvl' : '3', 'ship_per_hour' : '123'},
           {'planet_lvl' : '4', 'ship_per_hour' : '133'},
           {'planet_lvl' : '5', 'ship_per_hour' : '143'},
           {'planet_lvl' : '6', 'ship_per_hour' : '156'},
           {'planet_lvl' : '7', 'ship_per_hour' : '168'},
           {'planet_lvl' : '8', 'ship_per_hour' : '181'},
           {'planet_lvl' : '9', 'ship_per_hour' : '196'},
           {'planet_lvl' : '10', 'ship_per_hour' : '212'},
           {'planet_lvl' : '11', 'ship_per_hour' : '229'},
           {'planet_lvl' : '12', 'ship_per_hour' : '247'},
           {'planet_lvl' : '13', 'ship_per_hour' : '267'},
           {'planet_lvl' : '14', 'ship_per_hour' : '288'},
           {'planet_lvl' : '15', 'ship_per_hour' : '311'},
           {'planet_lvl' : '16', 'ship_per_hour' : '336'},
           {'planet_lvl' : '17', 'ship_per_hour' : '354'},
           {'planet_lvl' : '18', 'ship_per_hour' : '378'},
           {'planet_lvl' : '19', 'ship_per_hour' : '405'},
           {'planet_lvl' : '20', 'ship_per_hour' : '333'},
           {'planet_lvl' : '21', 'ship_per_hour' : '464'},
           {'planet_lvl' : '22', 'ship_per_hour' : '496'},
           {'planet_lvl' : '23', 'ship_per_hour' : '531'},
           {'planet_lvl' : '24', 'ship_per_hour' : '568'},
           {'planet_lvl' : '25', 'ship_per_hour' : '608'},
           {'planet_lvl' : '26', 'ship_per_hour' : '650'},
           {'planet_lvl' : '27', 'ship_per_hour' : '696'},
           {'planet_lvl' : '28', 'ship_per_hour' : '745'},
           {'planet_lvl' : '29', 'ship_per_hour' : '797'},
           {'planet_lvl' : '30', 'ship_per_hour' : '853'},
           {'planet_lvl' : '31', 'ship_per_hour' : '912'},
           {'planet_lvl' : '32', 'ship_per_hour' : '976'},
           {'planet_lvl' : '33', 'ship_per_hour' : '976'},
           {'planet_lvl' : '34', 'ship_per_hour' : '976'},
           {'planet_lvl' : '35', 'ship_per_hour' : '1196'},
           {'planet_lvl' : '36', 'ship_per_hour' : '1280'},
           {'planet_lvl' : '37', 'ship_per_hour' : '1280'},
           {'planet_lvl' : '38', 'ship_per_hour' : '1280'},
           {'planet_lvl' : '39', 'ship_per_hour' : '1280'},
           {'planet_lvl' : '40', 'ship_per_hour' : '1280'},]

fire1 = [{'planet_lvl' : '1', 'ship_per_hour' : '112'},
           {'planet_lvl' : '2', 'ship_per_hour' : '121'},
           {'planet_lvl' : '3', 'ship_per_hour' : '131'},
           {'planet_lvl' : '4', 'ship_per_hour' : '141'},
           {'planet_lvl' : '5', 'ship_per_hour' : '153'},
           {'planet_lvl' : '6', 'ship_per_hour' : '165'},
           {'planet_lvl' : '7', 'ship_per_hour' : '178'},
           {'planet_lvl' : '8', 'ship_per_hour' : '192'},
           {'planet_lvl' : '9', 'ship_per_hour' : '208'},
           {'planet_lvl' : '10', 'ship_per_hour' : '224'},
           {'planet_lvl' : '11', 'ship_per_hour' : '242'},
           {'planet_lvl' : '12', 'ship_per_hour' : '262'},
           {'planet_lvl' : '13', 'ship_per_hour' : '283'},
           {'planet_lvl' : '14', 'ship_per_hour' : '305'},
           {'planet_lvl' : '15', 'ship_per_hour' : '330'},]

fire3 = [{'planet_lvl' : '1', 'ship_per_hour' : '118'},
           {'planet_lvl' : '2', 'ship_per_hour' : '128'},
           {'planet_lvl' : '3', 'ship_per_hour' : '138'},
           {'planet_lvl' : '4', 'ship_per_hour' : '149'},
           {'planet_lvl' : '5', 'ship_per_hour' : '161'},
           {'planet_lvl' : '6', 'ship_per_hour' : '174'},
           {'planet_lvl' : '7', 'ship_per_hour' : '188'},
           {'planet_lvl' : '8', 'ship_per_hour' : '203'},
           {'planet_lvl' : '9', 'ship_per_hour' : '219'},
           {'planet_lvl' : '10', 'ship_per_hour' : '237'},
           {'planet_lvl' : '11', 'ship_per_hour' : '256'},
           {'planet_lvl' : '12', 'ship_per_hour' : '276'},
           {'planet_lvl' : '13', 'ship_per_hour' : '298'},
           {'planet_lvl' : '14', 'ship_per_hour' : '322'},
           {'planet_lvl' : '15', 'ship_per_hour' : '348'},
           {'planet_lvl' : '16', 'ship_per_hour' : '376'},
           {'planet_lvl' : '17', 'ship_per_hour' : '395'},
           {'planet_lvl' : '18', 'ship_per_hour' : '423'},
           {'planet_lvl' : '19', 'ship_per_hour' : '453'},
           {'planet_lvl' : '20', 'ship_per_hour' : '484'},
           {'planet_lvl' : '21', 'ship_per_hour' : '518'},
           {'planet_lvl' : '22', 'ship_per_hour' : '555'},
           {'planet_lvl' : '23', 'ship_per_hour' : '593'},
           {'planet_lvl' : '24', 'ship_per_hour' : '635'},
           {'planet_lvl' : '25', 'ship_per_hour' : '679'},
           {'planet_lvl' : '26', 'ship_per_hour' : '727'},
           {'planet_lvl' : '27', 'ship_per_hour' : '778'},
           {'planet_lvl' : '28', 'ship_per_hour' : '832'},
           {'planet_lvl' : '29', 'ship_per_hour' : '891'},
           {'planet_lvl' : '30', 'ship_per_hour' : '953'},]

fire4 = [{'planet_lvl' : '1', 'ship_per_hour' : '125'},
           {'planet_lvl' : '2', 'ship_per_hour' : '135'},
           {'planet_lvl' : '3', 'ship_per_hour' : '145'},
           {'planet_lvl' : '4', 'ship_per_hour' : '157'},
           {'planet_lvl' : '5', 'ship_per_hour' : '170'},
           {'planet_lvl' : '6', 'ship_per_hour' : '138'},
           {'planet_lvl' : '7', 'ship_per_hour' : '198'},
           {'planet_lvl' : '8', 'ship_per_hour' : '214'},
           {'planet_lvl' : '9', 'ship_per_hour' : '231'},
           {'planet_lvl' : '10', 'ship_per_hour' : '249'},
           {'planet_lvl' : '11', 'ship_per_hour' : '269'},
           {'planet_lvl' : '12', 'ship_per_hour' : '291'},
           {'planet_lvl' : '13', 'ship_per_hour' : '314'},
           {'planet_lvl' : '14', 'ship_per_hour' : '339'},
           {'planet_lvl' : '15', 'ship_per_hour' : '366'},
           {'planet_lvl' : '16', 'ship_per_hour' : '396'},
           {'planet_lvl' : '17', 'ship_per_hour' : '416'},
           {'planet_lvl' : '18', 'ship_per_hour' : '445'},
           {'planet_lvl' : '19', 'ship_per_hour' : '477'},
           {'planet_lvl' : '20', 'ship_per_hour' : '510'},
           {'planet_lvl' : '21', 'ship_per_hour' : '546'},
           {'planet_lvl' : '22', 'ship_per_hour' : '584'},
           {'planet_lvl' : '23', 'ship_per_hour' : '625'},
           {'planet_lvl' : '24', 'ship_per_hour' : '668'},
           {'planet_lvl' : '25', 'ship_per_hour' : '715'},
           {'planet_lvl' : '26', 'ship_per_hour' : '765'},
           {'planet_lvl' : '27', 'ship_per_hour' : '819'},
           {'planet_lvl' : '28', 'ship_per_hour' : '876'},
           {'planet_lvl' : '29', 'ship_per_hour' : '938'},
           {'planet_lvl' : '30', 'ship_per_hour' : '1003'},
           {'planet_lvl' : '31', 'ship_per_hour' : '1073'},
           {'planet_lvl' : '32', 'ship_per_hour' : '1149'},
           {'planet_lvl' : '33', 'ship_per_hour' : '1229'},
           {'planet_lvl' : '34', 'ship_per_hour' : '1229'},
           {'planet_lvl' : '35', 'ship_per_hour' : '1229'},
           {'planet_lvl' : '36', 'ship_per_hour' : '1506'},
           {'planet_lvl' : '37', 'ship_per_hour' : '1611'},
           {'planet_lvl' : '38', 'ship_per_hour' : '1611'},
           {'planet_lvl' : '39', 'ship_per_hour' : '1611'},
           {'planet_lvl' : '40', 'ship_per_hour' : '1611'},]

water1 = [{'planet_lvl' : '1', 'ship_per_hour' : '118'},
           {'planet_lvl' : '2', 'ship_per_hour' : '128'},
           {'planet_lvl' : '3', 'ship_per_hour' : '138'},
           {'planet_lvl' : '4', 'ship_per_hour' : '149'},
           {'planet_lvl' : '5', 'ship_per_hour' : '161'},
           {'planet_lvl' : '6', 'ship_per_hour' : '174'},
           {'planet_lvl' : '7', 'ship_per_hour' : '188'},
           {'planet_lvl' : '8', 'ship_per_hour' : '203'},
           {'planet_lvl' : '9', 'ship_per_hour' : '219'},
           {'planet_lvl' : '10', 'ship_per_hour' : '237'},
           {'planet_lvl' : '11', 'ship_per_hour' : '256'},
           {'planet_lvl' : '12', 'ship_per_hour' : '276'},
           {'planet_lvl' : '13', 'ship_per_hour' : '298'},
           {'planet_lvl' : '14', 'ship_per_hour' : '322'},
           {'planet_lvl' : '15', 'ship_per_hour' : '348'},]

water3 = [{'planet_lvl' : '1', 'ship_per_hour' : '125'},
           {'planet_lvl' : '2', 'ship_per_hour' : '135'},
           {'planet_lvl' : '3', 'ship_per_hour' : '145'},
           {'planet_lvl' : '4', 'ship_per_hour' : '157'},
           {'planet_lvl' : '5', 'ship_per_hour' : '170'},
           {'planet_lvl' : '6', 'ship_per_hour' : '183'},
           {'planet_lvl' : '7', 'ship_per_hour' : '198'},
           {'planet_lvl' : '8', 'ship_per_hour' : '214'},
           {'planet_lvl' : '9', 'ship_per_hour' : '231'},
           {'planet_lvl' : '10', 'ship_per_hour' : '249'},
           {'planet_lvl' : '11', 'ship_per_hour' : '269'},
           {'planet_lvl' : '12', 'ship_per_hour' : '291'},
           {'planet_lvl' : '13', 'ship_per_hour' : '314'},
           {'planet_lvl' : '14', 'ship_per_hour' : '339'},
           {'planet_lvl' : '15', 'ship_per_hour' : '366'},
           {'planet_lvl' : '16', 'ship_per_hour' : '396'},
           {'planet_lvl' : '17', 'ship_per_hour' : '416'},
           {'planet_lvl' : '18', 'ship_per_hour' : '445'},
           {'planet_lvl' : '19', 'ship_per_hour' : '477'},
           {'planet_lvl' : '20', 'ship_per_hour' : '510'},
           {'planet_lvl' : '21', 'ship_per_hour' : '546'},
           {'planet_lvl' : '22', 'ship_per_hour' : '584'},
           {'planet_lvl' : '23', 'ship_per_hour' : '625'},
           {'planet_lvl' : '24', 'ship_per_hour' : '668'},
           {'planet_lvl' : '25', 'ship_per_hour' : '715'},
           {'planet_lvl' : '26', 'ship_per_hour' : '765'},
           {'planet_lvl' : '27', 'ship_per_hour' : '819'},
           {'planet_lvl' : '28', 'ship_per_hour' : '876'},
           {'planet_lvl' : '29', 'ship_per_hour' : '938'},
           {'planet_lvl' : '30', 'ship_per_hour' : '1003'},]

water4 = [{'planet_lvl' : '1', 'ship_per_hour' : '131'},
           {'planet_lvl' : '2', 'ship_per_hour' : '141'},
           {'planet_lvl' : '3', 'ship_per_hour' : '153'},
           {'planet_lvl' : '4', 'ship_per_hour' : '165'},
           {'planet_lvl' : '5', 'ship_per_hour' : '178'},
           {'planet_lvl' : '6', 'ship_per_hour' : '192'},
           {'planet_lvl' : '7', 'ship_per_hour' : '208'},
           {'planet_lvl' : '8', 'ship_per_hour' : '224'},
           {'planet_lvl' : '9', 'ship_per_hour' : '242'},
           {'planet_lvl' : '10', 'ship_per_hour' : '262'},
           {'planet_lvl' : '11', 'ship_per_hour' : '283'},
           {'planet_lvl' : '12', 'ship_per_hour' : '305'},
           {'planet_lvl' : '13', 'ship_per_hour' : '330'},
           {'planet_lvl' : '14', 'ship_per_hour' : '356'},
           {'planet_lvl' : '15', 'ship_per_hour' : '385'},
           {'planet_lvl' : '16', 'ship_per_hour' : '415'},
           {'planet_lvl' : '17', 'ship_per_hour' : '437'},
           {'planet_lvl' : '18', 'ship_per_hour' : '468'},
           {'planet_lvl' : '19', 'ship_per_hour' : '500'},
           {'planet_lvl' : '20', 'ship_per_hour' : '535'},
           {'planet_lvl' : '21', 'ship_per_hour' : '573'},
           {'planet_lvl' : '22', 'ship_per_hour' : '613'},
           {'planet_lvl' : '23', 'ship_per_hour' : '656'},
           {'planet_lvl' : '24', 'ship_per_hour' : '702'},
           {'planet_lvl' : '25', 'ship_per_hour' : '751'},
           {'planet_lvl' : '26', 'ship_per_hour' : '804'},
           {'planet_lvl' : '27', 'ship_per_hour' : '860'},
           {'planet_lvl' : '28', 'ship_per_hour' : '920'},
           {'planet_lvl' : '29', 'ship_per_hour' : '920'},
           {'planet_lvl' : '30', 'ship_per_hour' : '1053'},
           {'planet_lvl' : '31', 'ship_per_hour' : '1053'},
           {'planet_lvl' : '32', 'ship_per_hour' : '1206'},
           {'planet_lvl' : '33', 'ship_per_hour' : '1206'},
           {'planet_lvl' : '34', 'ship_per_hour' : '1206'},
           {'planet_lvl' : '35', 'ship_per_hour' : '1478'},
           {'planet_lvl' : '36', 'ship_per_hour' : '1581'},
           {'planet_lvl' : '37', 'ship_per_hour' : '1581'},
           {'planet_lvl' : '38', 'ship_per_hour' : '1581'},
           {'planet_lvl' : '39', 'ship_per_hour' : '1581'},
           {'planet_lvl' : '40', 'ship_per_hour' : '1581'},]

terran1 = [{'planet_lvl' : '1', 'ship_per_hour' : '143'},
           {'planet_lvl' : '2', 'ship_per_hour' : '155'},
           {'planet_lvl' : '3', 'ship_per_hour' : '167'},
           {'planet_lvl' : '4', 'ship_per_hour' : '181'},
           {'planet_lvl' : '5', 'ship_per_hour' : '195'},
           {'planet_lvl' : '6', 'ship_per_hour' : '211'},
           {'planet_lvl' : '7', 'ship_per_hour' : '227'},
           {'planet_lvl' : '8', 'ship_per_hour' : '246'},
           {'planet_lvl' : '9', 'ship_per_hour' : '265'},
           {'planet_lvl' : '10', 'ship_per_hour' : '287'},
           {'planet_lvl' : '11', 'ship_per_hour' : '310'},
           {'planet_lvl' : '12', 'ship_per_hour' : '334'},
           {'planet_lvl' : '13', 'ship_per_hour' : '361'},
           {'planet_lvl' : '14', 'ship_per_hour' : '390'},
           {'planet_lvl' : '15', 'ship_per_hour' : '421'},]

terran3 = [{'planet_lvl' : '1', 'ship_per_hour' : '150'},
           {'planet_lvl' : '2', 'ship_per_hour' : '162'},
           {'planet_lvl' : '3', 'ship_per_hour' : '174'},
           {'planet_lvl' : '4', 'ship_per_hour' : '188'},
           {'planet_lvl' : '5', 'ship_per_hour' : '204'},
           {'planet_lvl' : '6', 'ship_per_hour' : '220'},
           {'planet_lvl' : '7', 'ship_per_hour' : '237'},
           {'planet_lvl' : '8', 'ship_per_hour' : '256'},
           {'planet_lvl' : '9', 'ship_per_hour' : '277'},
           {'planet_lvl' : '10', 'ship_per_hour' : '299'},
           {'planet_lvl' : '11', 'ship_per_hour' : '323'},
           {'planet_lvl' : '12', 'ship_per_hour' : '349'},
           {'planet_lvl' : '13', 'ship_per_hour' : '377'},
           {'planet_lvl' : '14', 'ship_per_hour' : '407'},
           {'planet_lvl' : '15', 'ship_per_hour' : '440'},
           {'planet_lvl' : '16', 'ship_per_hour' : '475'},
           {'planet_lvl' : '17', 'ship_per_hour' : '500'},
           {'planet_lvl' : '18', 'ship_per_hour' : '535'},
           {'planet_lvl' : '19', 'ship_per_hour' : '572'},
           {'planet_lvl' : '20', 'ship_per_hour' : '612'},
           {'planet_lvl' : '21', 'ship_per_hour' : '655'},
           {'planet_lvl' : '22', 'ship_per_hour' : '701'},
           {'planet_lvl' : '23', 'ship_per_hour' : '750'},
           {'planet_lvl' : '24', 'ship_per_hour' : '802'},
           {'planet_lvl' : '25', 'ship_per_hour' : '858'},
           {'planet_lvl' : '26', 'ship_per_hour' : '919'},
           {'planet_lvl' : '27', 'ship_per_hour' : '983'},
           {'planet_lvl' : '28', 'ship_per_hour' : '1052'},
           {'planet_lvl' : '29', 'ship_per_hour' : '1125'},
           {'planet_lvl' : '30', 'ship_per_hour' : '1204'},]

terran4 = [{'planet_lvl' : '1', 'ship_per_hour' : '156'},
           {'planet_lvl' : '2', 'ship_per_hour' : '168'},
           {'planet_lvl' : '3', 'ship_per_hour' : '182'},
           {'planet_lvl' : '4', 'ship_per_hour' : '196'},
           {'planet_lvl' : '5', 'ship_per_hour' : '212'},
           {'planet_lvl' : '6', 'ship_per_hour' : '229'},
           {'planet_lvl' : '7', 'ship_per_hour' : '247'},
           {'planet_lvl' : '8', 'ship_per_hour' : '267'},
           {'planet_lvl' : '9', 'ship_per_hour' : '289'},
           {'planet_lvl' : '10', 'ship_per_hour' : '312'},
           {'planet_lvl' : '11', 'ship_per_hour' : '337'},
           {'planet_lvl' : '12', 'ship_per_hour' : '363'},
           {'planet_lvl' : '13', 'ship_per_hour' : '393'},
           {'planet_lvl' : '14', 'ship_per_hour' : '424'},
           {'planet_lvl' : '15', 'ship_per_hour' : '458'},
           {'planet_lvl' : '16', 'ship_per_hour' : '495'},
           {'planet_lvl' : '17', 'ship_per_hour' : '520'},
           {'planet_lvl' : '18', 'ship_per_hour' : '557'},
           {'planet_lvl' : '19', 'ship_per_hour' : '596'},
           {'planet_lvl' : '20', 'ship_per_hour' : '638'},
           {'planet_lvl' : '21', 'ship_per_hour' : '682'},
           {'planet_lvl' : '22', 'ship_per_hour' : '730'},
           {'planet_lvl' : '23', 'ship_per_hour' : '781'},
           {'planet_lvl' : '24', 'ship_per_hour' : '836'},
           {'planet_lvl' : '25', 'ship_per_hour' : '894'},
           {'planet_lvl' : '26', 'ship_per_hour' : '957'},
           {'planet_lvl' : '27', 'ship_per_hour' : '1024'},
           {'planet_lvl' : '28', 'ship_per_hour' : '1095'},
           {'planet_lvl' : '29', 'ship_per_hour' : '1095'},
           {'planet_lvl' : '30', 'ship_per_hour' : '1254'},
           {'planet_lvl' : '31', 'ship_per_hour' : '1254'},
           {'planet_lvl' : '32', 'ship_per_hour' : '1436'},
           {'planet_lvl' : '33', 'ship_per_hour' : '1436'},
           {'planet_lvl' : '34', 'ship_per_hour' : '1644'},
           {'planet_lvl' : '35', 'ship_per_hour' : '1759'},
           {'planet_lvl' : '36', 'ship_per_hour' : '1759'},
           {'planet_lvl' : '37', 'ship_per_hour' : '1759'},
           {'planet_lvl' : '38', 'ship_per_hour' : '1759'},
           {'planet_lvl' : '39', 'ship_per_hour' : '1759'},
           {'planet_lvl' : '40', 'ship_per_hour' : '1759'},]

gas2 = [{'planet_lvl' : '1', 'ship_per_hour' : '150'},
           {'planet_lvl' : '2', 'ship_per_hour' : '162'},
           {'planet_lvl' : '3', 'ship_per_hour' : '174'},
           {'planet_lvl' : '4', 'ship_per_hour' : '188'},
           {'planet_lvl' : '5', 'ship_per_hour' : '204'},
           {'planet_lvl' : '6', 'ship_per_hour' : '220'},
           {'planet_lvl' : '7', 'ship_per_hour' : '237'},
           {'planet_lvl' : '8', 'ship_per_hour' : '256'},
           {'planet_lvl' : '9', 'ship_per_hour' : '277'},
           {'planet_lvl' : '10', 'ship_per_hour' : '299'},
           {'planet_lvl' : '11', 'ship_per_hour' : '323'},
           {'planet_lvl' : '12', 'ship_per_hour' : '349'},
           {'planet_lvl' : '13', 'ship_per_hour' : '377'},
           {'planet_lvl' : '14', 'ship_per_hour' : '407'},
           {'planet_lvl' : '15', 'ship_per_hour' : '440'},
           {'planet_lvl' : '16', 'ship_per_hour' : '475'},
           {'planet_lvl' : '17', 'ship_per_hour' : '500'},
           {'planet_lvl' : '18', 'ship_per_hour' : '535'},
           {'planet_lvl' : '19', 'ship_per_hour' : '572'},
           {'planet_lvl' : '20', 'ship_per_hour' : '612'},]

gas4 = [{'planet_lvl' : '1', 'ship_per_hour' : '156'},
           {'planet_lvl' : '2', 'ship_per_hour' : '168'},
           {'planet_lvl' : '3', 'ship_per_hour' : '182'},
           {'planet_lvl' : '4', 'ship_per_hour' : '196'},
           {'planet_lvl' : '5', 'ship_per_hour' : '212'},
           {'planet_lvl' : '6', 'ship_per_hour' : '229'},
           {'planet_lvl' : '7', 'ship_per_hour' : '247'},
           {'planet_lvl' : '8', 'ship_per_hour' : '267'},
           {'planet_lvl' : '9', 'ship_per_hour' : '289'},
           {'planet_lvl' : '10', 'ship_per_hour' : '312'},
           {'planet_lvl' : '11', 'ship_per_hour' : '337'},
           {'planet_lvl' : '12', 'ship_per_hour' : '363'},
           {'planet_lvl' : '13', 'ship_per_hour' : '393'},
           {'planet_lvl' : '14', 'ship_per_hour' : '424'},
           {'planet_lvl' : '15', 'ship_per_hour' : '458'},
           {'planet_lvl' : '16', 'ship_per_hour' : '495'},
           {'planet_lvl' : '17', 'ship_per_hour' : '520'},
           {'planet_lvl' : '18', 'ship_per_hour' : '557'},
           {'planet_lvl' : '19', 'ship_per_hour' : '596'},
           {'planet_lvl' : '20', 'ship_per_hour' : '638'},
           {'planet_lvl' : '21', 'ship_per_hour' : '682'},
           {'planet_lvl' : '22', 'ship_per_hour' : '730'},
           {'planet_lvl' : '23', 'ship_per_hour' : '781'},
           {'planet_lvl' : '24', 'ship_per_hour' : '836'},
           {'planet_lvl' : '25', 'ship_per_hour' : '894'},
           {'planet_lvl' : '26', 'ship_per_hour' : '957'},
           {'planet_lvl' : '27', 'ship_per_hour' : '1024'},
           {'planet_lvl' : '28', 'ship_per_hour' : '1095'},
           {'planet_lvl' : '29', 'ship_per_hour' : '1095'},
           {'planet_lvl' : '30', 'ship_per_hour' : '1254'},
           {'planet_lvl' : '31', 'ship_per_hour' : '1254'},
           {'planet_lvl' : '32', 'ship_per_hour' : '1436'},
           {'planet_lvl' : '33', 'ship_per_hour' : '1436'},
           {'planet_lvl' : '34', 'ship_per_hour' : '1436'},
           {'planet_lvl' : '35', 'ship_per_hour' : '1436'},
           {'planet_lvl' : '36', 'ship_per_hour' : '1436'},
           {'planet_lvl' : '37', 'ship_per_hour' : '2014'},
           {'planet_lvl' : '38', 'ship_per_hour' : '2155'},
           {'planet_lvl' : '39', 'ship_per_hour' : '2155'},
           {'planet_lvl' : '40', 'ship_per_hour' : '2155'},]

ice4 = [{'planet_lvl' : '1', 'ship_per_hour' : '175'},
           {'planet_lvl' : '2', 'ship_per_hour' : '189'},
           {'planet_lvl' : '3', 'ship_per_hour' : '204'},
           {'planet_lvl' : '4', 'ship_per_hour' : '220'},
           {'planet_lvl' : '5', 'ship_per_hour' : '238'},
           {'planet_lvl' : '6', 'ship_per_hour' : '257'},
           {'planet_lvl' : '7', 'ship_per_hour' : '277'},
           {'planet_lvl' : '8', 'ship_per_hour' : '277'},
           {'planet_lvl' : '9', 'ship_per_hour' : '277'},
           {'planet_lvl' : '10', 'ship_per_hour' : '277'},
           {'planet_lvl' : '11', 'ship_per_hour' : '277'},
           {'planet_lvl' : '12', 'ship_per_hour' : '277'},
           {'planet_lvl' : '13', 'ship_per_hour' : '440'},
           {'planet_lvl' : '14', 'ship_per_hour' : '440'},
           {'planet_lvl' : '15', 'ship_per_hour' : '513'},
           {'planet_lvl' : '16', 'ship_per_hour' : '554'},
           {'planet_lvl' : '17', 'ship_per_hour' : '583'},
           {'planet_lvl' : '18', 'ship_per_hour' : '624'},
           {'planet_lvl' : '19', 'ship_per_hour' : '667'},
           {'planet_lvl' : '20', 'ship_per_hour' : '714'},
           {'planet_lvl' : '21', 'ship_per_hour' : '764'},
           {'planet_lvl' : '22', 'ship_per_hour' : '818'},
           {'planet_lvl' : '23', 'ship_per_hour' : '875'},
           {'planet_lvl' : '24', 'ship_per_hour' : '936'},
           {'planet_lvl' : '25', 'ship_per_hour' : '1002'},
           {'planet_lvl' : '26', 'ship_per_hour' : '1072'},
           {'planet_lvl' : '27', 'ship_per_hour' : '1147'},
           {'planet_lvl' : '28', 'ship_per_hour' : '1227'},
           {'planet_lvl' : '29', 'ship_per_hour' : '1313'},
           {'planet_lvl' : '30', 'ship_per_hour' : '1405'},
           {'planet_lvl' : '31', 'ship_per_hour' : '1503'},
           {'planet_lvl' : '32', 'ship_per_hour' : '1608'},
           {'planet_lvl' : '33', 'ship_per_hour' : '1721'},
           {'planet_lvl' : '34', 'ship_per_hour' : '1721'},
           {'planet_lvl' : '35', 'ship_per_hour' : '1970'},
           {'planet_lvl' : '36', 'ship_per_hour' : '2108'},
           {'planet_lvl' : '37', 'ship_per_hour' : '2108'},
           {'planet_lvl' : '38', 'ship_per_hour' : '2108'},
           {'planet_lvl' : '39', 'ship_per_hour' : '2108'},
           {'planet_lvl' : '40', 'ship_per_hour' : '2108'},]

listers = [{'planet_type' : 'desert1', 'value': desert1},
           {'planet_type' : 'desert3', 'value': desert3},
           {'planet_type' : 'desert4', 'value': desert4},
           {'planet_type' : 'fire1', 'value': fire1},
           {'planet_type' : 'fire3', 'value': fire3},
           {'planet_type' : 'fire4', 'value': fire4},
           {'planet_type' : 'water1', 'value': water1},
           {'planet_type' : 'water3', 'value': water3},
           {'planet_type' : 'water4', 'value': water4},
           {'planet_type' : 'terran1', 'value': terran1},
           {'planet_type' : 'terran3', 'value': terran3},
           {'planet_type' : 'terran4', 'value': terran4},
           {'planet_type' : 'gas2', 'value': gas2},
           {'planet_type' : 'gas4', 'value': gas4},
           {'planet_type' : 'ice4', 'value': ice4},]

def planet_cap(lvl):#gets planet cap from level
    for n in planet_storages:
        if n['planet_lvl'] == lvl:
            return(n['credit_cap'])
def planet_lvl(cap):#gets level from planet cap
    for n in planet_storages:
        if n['credit_cap'] == cap:
            return(n['planet_lvl'])
def planet_cost(lvl):#gets planet cap from level
    for n in planet_storages:
        if n['planet_lvl'] == lvl:
            return(n['cost'])


def transfer(conca):
    for n in listers:
        if n['planet_type'] == conca:
            return(n['value'])
def temp(lists,level):
    temps = lists
    for i in temps:
        if i['planet_lvl'] == level:
            return(i['ship_per_hour'])
def credit_per_hour(planet_type,level,teirlvl):
    temporary = planet_type + teirlvl
    insert = transfer(temporary)
    credits_per_hour = temp(insert,level)
    return credits_per_hour


    
def max_levels_planet(planet_type,teirlvl):
    temporary = planet_type + teirlvl
    insert = transfer(temporary)
    final = insert[-1]
    return final.get('planet_lvl')
    
